### ISSUE TITLE
Exception in thread "LWJGL Application" java.lang.NullPointerException

### ISSUE THREAD

**Issue by darker0n** [oakes/play-clj#87]
Please, help me!
    
    Exception in thread "LWJGL Application" java.lang.NullPointerException
    at org.lwjgl.opengl.MacOSXContextImplementation.setSwapInterval(MacOSXContextImplementation.java:123)
    at org.lwjgl.opengl.ContextGL.setSwapInterval(ContextGL.java:232)
    at org.lwjgl.opengl.DrawableGL.setSwapInterval(DrawableGL.java:86)
    at org.lwjgl.opengl.Display.setSwapInterval(Display.java:1129)
    at org.lwjgl.opengl.Display.setVSyncEnabled(Display.java:1142)
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:446)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:118)

**Comment by darker0n** [comment]
I'm only restart REPL =)

**Comment by oakes** [comment]
What version of play-clj are you using? Are how are you restarting the REPL?

**Comment by oakes** [comment]
Don't run the main function more than once in the REPL. Unfortunately libGDX doesn't allow this to work.

**Comment by oakes** [comment]
Let me know if you have other questions about this.

**Comment by darker0n** [comment]
ok, thanks
